# Generated by Django 3.2.13 on 2022-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_watermarkalgorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark_type', models.CharField(max_length=128, unique=True)),
                ('model_type', models.CharField(max_length=128, unique=True)),
                ('algorithm_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
