# Generated by Django 3.2.13 on 2022-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_username_requestinfo_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='hash',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
