# Generated by Django 4.0.3 on 2022-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_requestinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendalgorithm',
            name='watermark_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
