# Generated by Django 3.2.13 on 2022-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220423_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('hash', models.CharField(max_length=128, unique=True)),
                ('watermark_type', models.CharField(max_length=128, null=True)),
                ('model_type', models.CharField(max_length=128, null=True)),
                ('timestamp', models.CharField(max_length=128, null=True)),
                ('key', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('watermark_type', models.CharField(max_length=128, null=True)),
                ('model_type', models.CharField(max_length=128, null=True)),
                ('key', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
