# Generated by Django 4.0.3 on 2022-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_requestinfo_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
    ]
