# Generated by Django 4.0.3 on 2022-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_recommendalgorithm_watermark_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
