# Generated by Django 4.0.3 on 2022-05-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_authenticationrecord_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128, unique=True)),
                ('judge_data_path', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
