# Generated by Django 4.0.3 on 2022-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_judgedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('hash', models.CharField(max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('authentication_hash', models.CharField(max_length=128, null=True)),
                ('judge_info', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
