# Generated by Django 3.2.13 on 2022-04-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220423_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMarkAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=128, unique=True)),
                ('algorithm_detail', models.CharField(max_length=128, null=True)),
                ('key_generate', models.CharField(max_length=128, null=True)),
                ('authentication_data_type', models.CharField(max_length=128, null=True)),
                ('verify_data_type', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
