# Generated by Django 3.2.13 on 2022-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_recommendalgorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128, unique=True)),
                ('authentication_data_path', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recommendalgorithm',
            name='algorithm_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recommendalgorithm',
            name='model_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
